### ISSUE TITLE
Certificate expiration alerts do not appear.

### ISSUE THREAD

**Issue by VikNorway** [albinbatman/zabbix-ssl-monitor-template#2]
Hello!

Recently, I have been using this script. It is very convenient because it takes hosts from the zabbix database. But I noticed that the certificate expiration alerts do not appear.
After examining the code, I realized that the SSL.php script incorrectly calculates the expiration date of the certificate. The command `php SSL.php example.com 10` never showed an error in the certificate expiration date. The error appeared only if the value of the third parameter is greater than or equal to the certificate validity period. For example, for Let's Encrypt, an error and a certificate expiration notification appeared only when the second parameter was set to 90 or more. That is, `php SSL.php example.com 90` has an error and an alert but `php SSL.php example.com 89` is not.
This is because the line `$expiresWithin = date ('Ym-d', strtotime ($ certificate-> validFrom." + {$ ExpiresWithin} day ");` in the script assumes that the certificate will never expire. `$expiresWithin` will always be greater than `$certificate->validTo`.
To fix this, you need to change the validateCertificate function to:
```
    private function validateCertificate($certificate, $expiresWithin)
    {
        $curDate = date ('Y-m-d');
        $expiresWithin = date('Y-m-d', strtotime($curDate . "+ {$expiresWithin} day"));
        if ($expiresWithin >= $certificate->validTo) {
            return true;
        } else {
            return false;
        }
    }
```
The validity period of the certificate will be compared to the current date plus the specified number of days. Thus, if `{$ EXPIRESWITHIN}` equals 10, then you will receive a notification 10 days before the certificate expires. 

BTW, I think proovek at https://github.com/albinbatman/zabbix-ssl-monitor-template/issues/1#issuecomment-744242842 talked about exactly this issue. 

Hope this helps someone.

**Comment by albinbatman** [comment]
I've updated the file with your changes - silly mistake :-)

Much appreciated!
